apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quizz-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/lutzkanov/project.git'  
    targetRevision: HEAD
    path: 'k8s'  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
