apiVersion: v1
kind: Service
metadata:
  name: quizz-app-service
spec:
  selector:
    app: quizz-app
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80   
  type: LoadBalancer   
